import { useState, useEffect } from 'react';
import { knowledgeLibraryApi } from '../../api/knowledge-library';
import { useTheme } from '../../hooks/useTheme';
import { useToast } from '../Toast';

interface KnowledgeAsset {
  id: string;
  title: string;
  category: string;
  content: string;
  tags: string[];
  confidence: number;
  reuseCount: number;
  createdDate: string;
}

const CATEGORIES = ['policy', 'framework', 'sop', 'template', 'playbook', 'guideline', 'best_practice', 'case_study', 'decision_model', 'reasoning_model'];

/**
 * Knowledge Library. The genuinely new entity this sprint — organizational
 * knowledge that isn't auto-generated by the pipeline had nowhere to live
 * before this. Reuse count is real, incremented server-side.
 */
export default function KnowledgeLibrary({ tenantId }: { tenantId: string }) {
  const theme = useTheme();
  const { showToast } = useToast();
  const [assets, setAssets] = useState<KnowledgeAsset[]>([]);
  const [categoryFilter, setCategoryFilter] = useState('');
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('best_practice');
  const [content, setContent] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      setAssets(await knowledgeLibraryApi.list(tenantId, categoryFilter || undefined));
    } catch (e: any) {
      showToast('error', e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [tenantId, categoryFilter]);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      await knowledgeLibraryApi.create({ tenantId, title, category, content });
      showToast('success', 'Knowledge asset added');
      setTitle(''); setContent(''); setShowForm(false);
      await load();
    } catch (e: any) {
      showToast('error', e.message);
    } finally {
      setSubmitting(false);
    }
  };

  const markReused = async (id: string) => {
    await knowledgeLibraryApi.markReused(tenantId, id);
    showToast('info', 'Marked as reused');
    await load();
  };

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: 1000, margin: '0 auto', padding: 24, backgroundColor: theme.bg, color: theme.text, minHeight: '100vh' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <h1>Knowledge Library</h1>
        <button onClick={() => setShowForm((s) => !s)}>{showForm ? 'Cancel' : '+ Add Knowledge'}</button>
      </header>

      {showForm && (
        <form onSubmit={submit} style={{ padding: 16, borderRadius: 8, border: `1px solid ${theme.border}`, backgroundColor: theme.surface, marginBottom: 24, display: 'grid', gap: 8 }}>
          <input placeholder="Title" value={title} onChange={(e) => setTitle(e.target.value)} required style={{ padding: 8, borderRadius: 6, border: `1px solid ${theme.border}`, backgroundColor: theme.bg, color: theme.text }} />
          <select value={category} onChange={(e) => setCategory(e.target.value)} style={{ padding: 8, borderRadius: 6, border: `1px solid ${theme.border}`, backgroundColor: theme.bg, color: theme.text }}>
            {CATEGORIES.map((c) => <option key={c} value={c}>{c.replace('_', ' ')}</option>)}
          </select>
          <textarea placeholder="Content" value={content} onChange={(e) => setContent(e.target.value)} required style={{ padding: 8, borderRadius: 6, border: `1px solid ${theme.border}`, backgroundColor: theme.bg, color: theme.text, minHeight: 100 }} />
          <button type="submit" disabled={submitting}>{submitting ? 'Saving...' : 'Save'}</button>
        </form>
      )}

      <div style={{ display: 'flex', gap: 6, marginBottom: 16, flexWrap: 'wrap' }}>
        <button onClick={() => setCategoryFilter('')} style={{ fontSize: 11, backgroundColor: !categoryFilter ? '#3b82f620' : 'transparent' }}>All</button>
        {CATEGORIES.map((c) => (
          <button key={c} onClick={() => setCategoryFilter(c)} style={{ fontSize: 11, backgroundColor: categoryFilter === c ? '#3b82f620' : 'transparent' }}>{c.replace('_', ' ')}</button>
        ))}
      </div>

      {loading ? (
        <div>Loading...</div>
      ) : assets.length === 0 ? (
        <p style={{ color: theme.textMuted }}>No knowledge assets yet.</p>
      ) : (
        <div style={{ display: 'grid', gap: 8 }}>
          {assets.map((a) => (
            <div key={a.id} style={{ padding: 14, borderRadius: 8, border: `1px solid ${theme.border}`, backgroundColor: theme.surface }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <strong>{a.title}</strong>
                <span style={{ fontSize: 10, color: theme.textMuted, textTransform: 'uppercase' }}>{a.category.replace('_', ' ')}</span>
              </div>
              <p style={{ fontSize: 13, color: theme.textMuted, margin: '6px 0' }}>{a.content}</p>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: 11, color: theme.textMuted }}>Reused {a.reuseCount}×</span>
                <button onClick={() => markReused(a.id)} style={{ fontSize: 11 }}>Mark as Used</button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
