-- Migration: 021_knowledge_assets.sql
-- Company Brain & Organizational Memory sprint. The genuinely new piece:
-- most of "Organizational Memory" already exists as Decision/Outcome/
-- Learning/Policy. What has never existed is a place for knowledge that
-- ISN'T generated by the automated Signal->Evidence->Learning pipeline: a
-- person manually documenting a best practice, playbook, SOP, or case study.

CREATE TABLE IF NOT EXISTS knowledge_assets (
  id                VARCHAR(36) PRIMARY KEY,
  tenant_id         VARCHAR(36) NOT NULL,
  title             TEXT NOT NULL,
  category          VARCHAR(255) NOT NULL,
  content           TEXT NOT NULL,
  tags              JSON NOT NULL DEFAULT '[]',
  confidence        NUMERIC NOT NULL DEFAULT 0.7,
  department_id     VARCHAR(36),
  related_person_ids JSON NOT NULL DEFAULT '[]',
  related_capability_ids JSON NOT NULL DEFAULT '[]',
  reuse_count       INTEGER NOT NULL DEFAULT 0,
  status            TEXT NOT NULL DEFAULT 'active',
  created_by        TEXT NOT NULL,
  created_date      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_knowledge_assets_tenant ON knowledge_assets (tenant_id, category);
CREATE INDEX idx_knowledge_assets_department ON knowledge_assets (tenant_id, department_id);
